### ISSUE TITLE
bioconductor stats for badges?

### ISSUE THREAD

**Issue by rmflight** [metacran/cranlogs.app#13]
Would it be possible to use the bioconductor package listing and download stats to provide download and availability badges for packages on bioconductor?

Stats here: http://www.bioconductor.org/packages/stats/

**Comment by gaborcsardi** [comment]
Hmmm. I think BioC support is reasonable in the long run. The ideal solution would be to get the daily numbers from BioC, because then I could use the same code. Do you know if they have daily numbers? Do you know whom I should contact to get them?

**Comment by rmflight** [comment]
The two names I normally see with respect to support on their end is Dan Tenenbaum (@dtenenba) and Marc Carlson (who I don't see on github), but @pshannon-bioc is another bioconductor person on github who might know something.

**Comment by rmflight** [comment]
BTW, I'm sure they have daily numbers somewhere, but the web interface is aggregating things. For example, my package [categoryCompare](http://bioconductor.org/packages/stats/bioc/categoryCompare.html) as of May  5 has only 19 downloads, when a normal month has ~ 300.

**Comment by dtenenba** [comment]
The github IDs of the people on the bioconductor team are listed [here](https://github.com/orgs/Bioconductor/people). What you're asking for has been requested before. I'm actually working right now on some shields for the package landing pages on the Bioconductor web site. If you are talking about shields that would be appropriate for a github repository, that's something a bit different that I may not be able to get to right away. If you want to roll your own shields based on the build output, you might look at the [build status database](http://bioconductor.org/checkResults/devel/bioc-LATEST/STATUS_DB.txt) ([release version](http://bioconductor.org/checkResults/release/bioc-LATEST/STATUS_DB.txt)) which is a condensed, machine-readable version of the [build report](http://bioconductor.org/checkResults/devel/bioc-LATEST/). We don't have an equivalent for package downloads. Maybe you could spell out exactly what you are asking for -- daily download numbers per package? And where you were planning to use these shields. Note that the download numbers we do have do not include mirrors. If someone is using a mirror near them instead of bioconductor.org, their downloads are not reflected in the numbers we publish.

**Comment by gaborcsardi** [comment]
>  ... Maybe you could spell out exactly what you are asking for -- daily download numbers per package? And where you were planning to use these shields. ...

This is what we have for CRAN packages:
> Download counts and badges: https://github.com/metacran/cranlogs.app  
`http://cranlogs.r-pkg.org/badges/stringr`  
![](http://cranlogs.r-pkg.org/badges/stringr)

Version badges (this is not yet documented properly): 
> `http://www.r-pkg.org/badges/version/stringr`  
![](http://www.r-pkg.org/badges/version/stringr)

I guess @rmflight is asking for the same for BioC packages. 

If you are already working on this, then all is fine, I guess, and I can just close this issues.

**Comment by dtenenba** [comment]
Well, as I said, what I'm working on is a bit different. I wasn't providing shields for general use and perhaps I still should. So let's keep the issue open for now.

**Comment by gaborcsardi** [comment]
> Well, as I said, what I'm working on is a bit different. I wasn't providing shields for general use 

I am not sure what you mean by this. They are for internal BioC use only? Or you put them on the BioC web pages? I guess the latter is good enough, because people can just link them there.

**Comment by dtenenba** [comment]
So a typical bioconductor package landing page currently looks like this:

http://bioconductor.org/packages/release/bioc/html/limma.html

My plan is to put a bunch of shields right after the package name at the top. When I generate the page I will generate an img tag like this:

&lt;img border="0" src="https://img.shields.io/badge/availability-all-platforms-green.svg"&gt;

That's not a shield that anyone else can reuse because the underlying data (that the build is ok on all platforms) is embedded in the html. So I might need to rethink the way I'm doing this to make it more generally useful. If instead I saved that shield to a known location such as 

http://bioconductor.org/shields/build/release/limma.svg

then anyone, anywhere could link to it. So stay tuned....

**Comment by rmflight** [comment]
Cool idea on having shields at the top next to package name.

I think the second option is more generally useful, @dtenenba. I also think it would be awesome to have the download stats available in a format outside of the html pages so that others can make use of it in other ways.

**Comment by dtenenba** [comment]
We've implemented some shields. Hopefully they meet your needs. See https://stat.ethz.ch/pipermail/bioc-devel/2015-May/007500.html for more information.

**Comment by gaborcsardi** [comment]
Great!

**Comment by rmflight** [comment]
They look pretty nice @dtenenba! Thanks
